/* export const servicios = [
  {
    'DISEÑO WEB': [
      'DISEÑO WEB A MEDIDA',
      'E-COMMERCE (TIENDA ONLINE)',
      'DISEÑO WEB CATÁLOGO',
      'DISEÑO WEB CORPORATIVO',
      'DISEÑO WEB EMPRESA',
      'DISEÑO WEB PYME',
      'DISEÑO WEB PORTAL',
      'DISEÑO WEB INTRANET',
      'DISEÑO WEB MINI SITIOS',
      'APLICACIONES MOVILES',
      'APP WEB MÓVILES',
      'INTEGRACIÓN WEBPAY PLUS',
      'MANTENCIÓN WEB',
    ],
    AGENCIA: {
      PUBLICIDAD: [
        'CAMPAÑAS',
        'PUBLICIDAD ONLINE',
        'PUBLICIDAD AL AIRE LIBRE',
        'PUBLICIDAD IMPRESA',
        'PUBLICIDAD MEDIOS SOCIALES',
        'PUBLICIDAD EN TRANSPORTE',
      ],
      BRANDING: [
        'ESTRATEGIA DE MARCA',
        'IDENTIDAD DE MARCA',
        'DISEÑO DE LOGO',
        'DIRECTRICES DE LA MARCA',
        'REDACCIÓN DE TEXTOS',
        'DIRECTRICES DE VOZ',
        'REBRANDING',
        'FOTOGRAFÍA / DIRECCIÓN',
        'DISEÑO INFOGRÁFICO',
      ],
      DIGITAL: [
        'DISEÑO DE PÁGINAS WEB',
        'DESARROLLO WEB',
        'GESTIÓN DE CONTENIDOS',
        'DISEÑO WEB RESPONSIVE',
        'E-COMMERCE',
        'OPTIMIZACIÓN BUSCADORES',
        'WEB HOSTING',
        'EMAIL MARKETING',
        'SOCIAL MEDIA',
      ],
      IMPRESIÓN: [
        'DISEÑO REPORTE ANUAL',
        'DISEÑO DE BROCHURE',
        'EMAIL MARKETING DIRECTO',
        'EXHIBIDORES / DISPLAY',
        'DISEÑO DE REVISTAS',
        'PACKAGING',
        'GESTIÓN DE IMPRESIÓN',
        'IMPRESION DE REPORTES',
        'DISEÑO DE SEÑALETICA',
        'DISEÑO DE PAPELERÍA',
      ],
      VIDEO: [
        'ANIMACIÓN',
        'VÍDEOS CORPORATIVOS',
        'MOTION GRAPHICS',
        'PRODUCCIÓN DE VÍDEOS',
        'VIDEO PROMOCIONAL',
      ],
    },
    'DISEÑO GRÁFICO': [
      'NAMING',
      'IDENTIDAD CORPORATIVA',
      'DISEÑO PAPELERÍA',
      'DISEÑO PUBLICITARIO',
      'DISEÑO PACKING',
      'DISEÑO LOGO',
      'DISEÑO DE CATÁLOGOS',
      'DISEÑO TARJETAS',
      'DISEÑO DE FOLLETOS',
      'DISEÑO FLYER',
    ],
    MARKETING: [
      'PUBLICIDAD EN FACEBOOK',
      'PUBLICIDAD EN GOOGLE',
      'EMAIL MARKETING',
      'SOCIAL MEDIA',
      'PUBLICIDAD EN TWITTER',
      'PUBLICIDAD EN YOUTUBE',
      'PUBLICIDAD EN WAZE',
    ],
    HOSTING: [
      'SERVIDORES DEDICADOS',
      'SERVIDORES SEMI-DEDICADOS',
      'VPS',
      'WEB HOSTING RESELLER',
      'WEB HOSTING CORPORATIVO',
      'WEB HOSTING EMPRESA',
      'HOSTING PYME',
      'STREAMING AUDIO',
      'STREAMING VIDEO',
    ],
    PORTAFOLIO: [ 'CASOS DE HECHITO', 'CLIENTES'],
    CONTACTANOS: ' ',
  },
];
*/

export const servicios = [
    {
      'DISEÑO WEB': [
        'DISEÑO WEB A MEDIDA',
        'E-COMMERCE (TIENDA ONLINE)',
        'DISEÑO WEB CATÁLOGO',
        'DISEÑO WEB CORPORATIVO',
        'DISEÑO WEB EMPRESA',
        'DISEÑO WEB PYME',
        'DISEÑO WEB PORTAL',
        'DISEÑO WEB INTRANET',
        'DISEÑO WEB MINI SITIOS',
        'APLICACIONES MOVILES',
        'APP WEB MÓVILES',
        'INTEGRACIÓN WEBPAY PLUS',
        'MANTENCIÓN WEB',
      ],
      PUBLICIDAD: [
        'CAMPAÑAS',
        'PUBLICIDAD ONLINE',
        'PUBLICIDAD AL AIRE LIBRE',
        'PUBLICIDAD IMPRESA',
        'PUBLICIDAD MEDIOS SOCIALES',
        'PUBLICIDAD EN TRANSPORTE',
      ],
      BRANDING: [
        'ESTRATEGIA DE MARCA',
        'IDENTIDAD DE MARCA',
        'DISEÑO DE LOGO',
        'DIRECTRICES DE LA MARCA',
        'REDACCIÓN DE TEXTOS',
        'DIRECTRICES DE VOZ',
        'REBRANDING',
        'FOTOGRAFÍA / DIRECCIÓN',
        'DISEÑO INFOGRÁFICO',
      ],
      DIGITAL: [
        'DISEÑO DE PÁGINAS WEB',
        'DESARROLLO WEB',
        'GESTIÓN DE CONTENIDOS',
        'DISEÑO WEB RESPONSIVE',
        'E-COMMERCE',
        'OPTIMIZACIÓN BUSCADORES',
        'WEB HOSTING',
        'EMAIL MARKETING',
        'SOCIAL MEDIA',
      ],
      IMPRESIÓN: [
        'DISEÑO REPORTE ANUAL',
        'DISEÑO DE BROCHURE',
        'EMAIL MARKETING DIRECTO',
        'EXHIBIDORES / DISPLAY',
        'DISEÑO DE REVISTAS',
        'PACKAGING',
        'GESTIÓN DE IMPRESIÓN',
        'IMPRESION DE REPORTES',
        'DISEÑO DE SEÑALETICA',
        'DISEÑO DE PAPELERÍA',
      ],
      VIDEO: [
        'ANIMACIÓN',
        'VÍDEOS CORPORATIVOS',
        'MOTION GRAPHICS',
        'PRODUCCIÓN DE VÍDEOS',
        'VIDEO PROMOCIONAL',
      ],
    },
  ];
  
